### ISSUE TITLE
Font weight semibold missing as Lexicon defines

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#3664]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

https://codesandbox.io/s/holy-sky-xdx4t

## Current status

- Lexicon definition: https://liferay.design/lexicon/foundations/typography/#font-weight

- `_utilities-functional-important.scss`:

```css
// Font Weight and Italics

.font-weight-light {
	font-weight: $font-weight-light !important;
}

.font-weight-lighter {
	font-weight: $font-weight-lighter !important;
}

.font-weight-normal {
	font-weight: $font-weight-normal !important;
}

.font-weight-bold {
	font-weight: $font-weight-bold !important;
}

.font-weight-bolder {
	font-weight: $font-weight-bolder !important;
}
```

## What is the expected result?

Font weight semi bold is available to use (600).

<img width="368" alt="Screenshot 2020-08-28 at 17 08 45" src="https://user-images.githubusercontent.com/15845466/91583276-40fa7500-e951-11ea-94a2-224493d1b9fa.png">

Thanks!
