### ISSUE TITLE
Uppercase in label-lg is optional

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#385]
Based on https://lexicondesign.io/docs/patterns/labels.html

SIZE | USAGE
--- | ---
Small | Use it in contexts where its relevante is not major. **Use it always in capital letters**.
Default | Use it for marking states. **The use of lowercase is valid in this option**

Currently, we don't allow lowercase in the default state since we have:

```css
.label {
    ...
    text-transform: uppercase;
    ...
}
```
