### ISSUE TITLE
Portal CSS modal inline-scroller class to Clay

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#4113]
## This pattern looks like a general need in Liferay portal, can we add it to Clay in some way?

```scss
@media (min-height: 400px) {
	.modal-body.inline-scroller {
		max-height: 320px;
	}
}
```

Right now it is a CSS file included in the module `frontend-css-web`, wich we want to remove

Should be this pattern of max-height validated by Lexicon? @drakonux
