### ISSUE TITLE
Can't use css variables in $font-size-base and other font size sass variables.

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#4393]
I want to be able to use style books to set font-size sass variables but the theme will not compile.

```
// Fonts

$font-size-base: var(--font-size-base);
$font-size-lg: var(--font-size-lg);
$font-size-sm: var(--font-size-sm);
```

**Comment by pat270** [comment]
@ethib137 Sorry I think we're going to have to wait on this one. We run too many calculations based on `$font-size-base`. We will definitely have nested calc functions which will be breaking for 7.3 users that still need limited IE11 support.

I think the best way around this at the moment is to use the CSS variable directly in the components you want it to apply to, for example:

```scss
$c-body: (
    font-size: var(--font-size-base),
);
$lead-font-size: calc(var(--font-size-base) * 1.25) !default;
$blockquote-font-size: calc(var(--font-size-base) * 1.25) !default;
$custom-control: (
	label: (
		font-size: var(--font-size-base),
	),
);
$dropdown-font-size: var(--font-size-base);
$dropdown-item-base: (
	c-kbd-inline: (
		line-height: calc(#{$dropdown-font-size} * #{$line-height-base}),
	),
);
```
