### ISSUE TITLE
@clayui/css: Links with icon have too little space between text and icon

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5382]
We need to remove the style

```css
a .inline-item-after {
  margin-left: 0.25rem;
}
```

There was a misunderstanding about the spacing between text and icon in links in https://github.com/liferay/clay/issues/5283. It should be 8px unless it is in the breadcrumb component. We can specify spacing between icon and text in each component so we don't need to add anything else.
