### ISSUE TITLE
@clayui/css: More complex input-groups should accommodate inset focus styles

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5487]
In the search bar example at https://clayui.com/docs/components/autocomplete/markup.html#css-loading, we manage the focus styling by adding the `focus` class to the parent `input-group-item` element. If we use an inset `box-shadow` the focus styles are no longer visible due to it being covered by the background of the input and buttons. We should move the focus style to a pseudo element to accommodate more types of focus borders.

Edit:
The clayui.com example doesn't add the `focus` class on `input-group-item`, but you can see it if you manually add it via dev tools. The bug we want to fix:

```css
.input-group-item.focus {
  box-shadow: inset 0 0 0 0.125rem #528eff, inset 0 0 0 0.25rem #fff;
}
```

doesn't show the focus outline. It's hidden beind the `input`. We can fix it by moving the focus shadow to a pseudo element using:

```css
.input-group-item.focus::after {
  border-radius: inherit;
  bottom: 0;
  box-shadow: inset 0 0 0 0.125rem #528eff, inset 0 0 0 0.25rem #fff;
  content: '';
  display: block;
  left: 0;
  pointer-events: none;
  position: absolute;
  right: 0;
  top: 0;
}
```

The component we need to update is located [here](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_input-groups.scss#L129-L131). It uses [this mixin](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/mixins/_input-groups.scss#L296). The properties are generated from the values [here](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/variables/_forms.scss#L1428-L1471).

We will need to move the `box-shadow` property to:

```
focus: (
  border-radius: clay-enable-rounded($input-border-radius),
  after: (
    box-shadow: $input-focus-box-shadow,
  ),
),
```
and it should generate the css:

```css
.input-group-item.focus::after {
  border-radius: inherit;
  bottom: 0;
  box-shadow: 0 0 0 0.125rem #fff, 0 0 0 0.25rem #528eff;
  content: '';
  display: block;
  left: 0;
  pointer-events: none;
  position: absolute;
  right: 0;
  top: 0;
}
```
